config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users
  resources :users, only: %i[index show destroy]

  resources :projects, only: %i[index show] do
    member do
      post :join
    end
    resources :topics, only: :create
    resources :tasks, only: :create
  end

  resources :tasks, only: %i[update destroy] do
    member do
      post :join
    end
  end
  resources :topics, only: %i[update destroy]

  resource :my, only: :show, controller: :my do
    get :projects
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :object, polymorphic: true
  belongs_to :sub_object, polymorphic: true, optional: true
  belongs_to :user

  enum notification_type: %i[
    new_project
    join_to_project
    new_user
    join_to_task
  ]
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_users
  has_many :users, through: :project_users
  has_many :tasks
  has_many :topics, -> { order(position: :asc) }

  after_create :create_topic
  after_create :notification_all_users

  enum currency: {
    "$": 0,
    "₴": 1,
    "€": 2,
  }

  scope :finished, -> { where("finish_at < ?",DateTime.now)}

  def in_team?(user)
    users.include?(user)
  end

  def next_topic_position
    topics.any? ? topics.last.position+1 : 0
  end

  private

  def create_topic
    topics.create(name: "Задачі", position: 0)
    topics.create(name: "Взято до виконання", position: 1)
    topics.create(name: "На перевірці", position: 2)
    topics.create(name: "Виконано", position: 3)
  end

  def notification_all_users
    User.find_each do |user|
      Notification.create!(object: self, user: user, notification_type: :new_project)
    end
  end
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :user
  belongs_to :project

  after_create :notification_about_join

  private

  def notification_about_join
    project.users.find_each do |some_user|
      next if some_user.id == user_id
      Notification.create!(
        object: project,
        sub_object: user,
        user: some_user,
        notification_type: :join_to_project
      )
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project, counter_cache: true
  belongs_to :topic
  has_many :task_users
  has_many :users, through: :task_users

  has_rich_text :description
end

app/models/task_user.rb
class TaskUser < ApplicationRecord
  belongs_to :user
  belongs_to :task

  delegate :project, to: :task

  after_create :notification_about_join

  private

  def notification_about_join
    project.users.find_each do |some_user|
      next if some_user.id == user_id
      Notification.create!(
        object: task,
        sub_object: user,
        user: some_user,
        notification_type: :join_to_task
      )
    end
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :project
  has_many :tasks, -> { order(position: :asc) }

  def next_task_position
    tasks.any? ? tasks.last.position+1 : 0 
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :project_users
  has_many :projects, through: :project_users
  has_many :tasks
  has_many :notifications

  after_create :notification_all_users

  enum position: {
    "Стажор": 0,
    "Дизайнер": 1,
    "Front-end": 2,
    "Backend": 3,
    "Піар менеджер": 4,
    "Project Menager": 5,
    "Директор": 6
  }

  def name
    email.split('@')[0]
  end

  private

  def notification_all_users
    User.find_each do |user|
      next if user.id == id
      Notification.create!(object: self, user: user, notification_type: :new_user)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/my_controller.rb
class MyController < ApplicationController
  before_action :authenticate_user!
  before_action :user

  def show; end

  def projects
    @projects = @user.projects.order(finish_at: :desc) 
  end

  private

  def user
    @user ||= current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def home
    @notifications_by_month = current_user.notifications.order(created_at: :desc).group_by { |m| m.created_at.beginning_of_month}
  end
end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :user_in_team, only: :show
  before_action :user_not_in_team, only: :join

  def index
    @projects = Project.where.not(id: current_user.projects.ids).order(finish_at: :asc) 
  end

  def show
    @users = project.users 
    @topics = project.topics
  end

  def join
    project.users << current_user
    redirect_to project
  end

  private

  def project
    @project ||= Project.find(params[:id])
  end

  def user_in_team
    redirect_back(fallback_location: root_path) unless project.in_team?(current_user)
  end

  def user_not_in_team
    redirect_back(fallback_location: root_path) if project.in_team?(current_user)
  end
end

app/controllers/tasks_controller.rb
class TasksController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :user_in_team

  def create
    @task = Task.new(task_params)
    task.position = topic.next_task_position
    task.project = project
    task.user = current_user
    task.save
    respond_to do |format|
      format.turbo_stream
    end
  end

  def update
    @old_topic = task.topic
    task.update(task_params)
    @topic = task.topic
    respond_to do |format|
      format.turbo_stream
    end
  end

  def destroy
    @topic = task.topic
    task.destroy
    respond_to do |format|
      format.turbo_stream
    end
  end

  def join
    task.users << current_user
    redirect_to project
  end

  private

  def topic
    @topic ||= Topic.find(task_params[:topic_id])
  end

  def task
    @task ||= Task.find(params[:id])
  end

  def project
    @project ||= (Project.find(params[:project_id]) if params[:project_id])|| task.project
  end

  def user_in_team
    redirect_back(fallback_location: root_path) unless project.in_team?(current_user)
  end

  def task_params
    params.require(:task).permit(:name, :description, :complated, :topic_id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :user_in_team

  def create
    @topic = Topic.new(topic_params)
    topic.position = project.next_topic_position
    topic.project = project
    topic.save
    respond_to do |format|
      format.turbo_stream
    end
  end

  def update
    topic.update(topic_params)
    respond_to do |format|
      format.turbo_stream
    end
  end

  def destroy
    topic.destroy
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def topic
    @topic ||= Topic.find(params[:id])
  end

  def project
    @project ||= Project.find(params[:project_id])
  end

  def user_in_team
    redirect_back(fallback_location: root_path) unless project.in_team?(current_user)
  end

  def topic_params
    params.require(:topic).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_helper.rb
module MyHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light ">
  <div class="container">
    <button class="navbar-toggler shadow-none" type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarCollapse">
      <span class="navbar-toggler-icon"><i
          class="fa fa-bars" aria-hidden="true"
          style="color:#e6e6ff"></i></span>
    </button>
    <div>
      <%= link_to root_path, class:"navbar-brand"  do %>
        <%= image_tag "/logo.svg",  height: 60 %>
      <%end%>
    </div>
    <div class="collapse navbar-collapse"
      id="navbarCollapse">
      <ul
        class="navbar-nav ms-auto align-items-center mb-lg-0">
        <li class="nav-item">
          <%= link_to projects_my_path ,class:"nav-link  me-3"  do %>
            Мої проекти
          <%end%>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "/user.svg",class:"cursor_pointer" ,id:"dropdownMenuButton1",data:{bs_toggle:"dropdown"}, height: 60, alt: current_user.email, title: current_user.email %>
          <div class="navcard dropdown-menu p-0 dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
            <div class="info px-4 pt-4">
              <h5 class="colored"><%= current_user.name%></h5>
              <p><%== "Вік: <b>#{(Date.current.year - current_user.birthday_at.year)}</b> років" if current_user.birthday_at%></p>
              <p>Працює від: <span><%= current_user.created_at.strftime("%d.%m.%Y")%></span></p>
              <p>Посада: <span><%= current_user.position%></span></p>
              <p>Виконані проекти: <span><%= current_user.projects.finished.count%></span></p>
              <p class="mb-4">Всього проектів: <span><%= current_user.projects.count%></span></p>
            </div>
            <div class="exit mt-auto p-0 w-100 text-center">
              <%= link_to destroy_user_session_path, class:"colored nav-link", method: :delete do%>
                Вихід
              <%end%>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="bottom_of_navbar d-flex align-items-center ">
  <div class="container">
    <ul class="navbar-nav flex-sm-row">
      <li class="nav-item nav-item__margin ">
        <%= link_to root_path, class:"nav-link"  do %>
          Головна
        <%end%>
      </li>
      <li class="nav-item nav-item__margin ">
        <%= link_to projects_path, class:"nav-link"  do %>
          Проекти
        <%end%>
      </li>
      <li class="nav-item nav-item__margin ">
        <%= link_to users_path, class:"nav-link"  do %>
          Персонал
        <%end%>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoTDMSiiC</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.0.6/dist/css/splide.min.css">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div class="container mb-5">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.0.6/dist/js/splide.min.js"></script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoTDMSiiC</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/my/_project.html.erb
<div class="col-12 col-md-3">
  <%= link_to project, class:"mb-3 #{ "disable" if ((project.finish_at.to_date - DateTime.now.to_date).to_i) < 0}" do %>
    <div class="Box Box__card Box__small d-flex justify-content-center align-items-center mb-4">
        <h5 class="text-center"> <%= project.name %></h5>
        <div class="badge bage bage__bottom">
          <%= ((project.finish_at.to_date - DateTime.now.to_date).to_i) < 0 ? "Проект завершено" : "Залишилось #{ (project.finish_at.to_date - DateTime.now.to_date).to_i} днів"%>
          
        </div>
    </div>
  <%end%>
</div>

app/views/my/projects.html.erb
<h1 class="text-center Box__maintitle my-5">Мої проекти</h1>
<div class="row">
  <%= render partial: "project", collection: @projects %>
</div>

app/views/my/show.html.erb
<h1><%=@user.email%></h1>

app/views/notifications/_notification.html.erb
<div class="Box Box__notification row <%= 'Box__yellow' if notification.notification_type == "new_user" %> <%='Box__red' if notification.notification_type == "new_project" %>">
  <div class="col-2">
    <%= notification.created_at.strftime("%e.%m.%Y")%>
  </div>
  <div class="col-2 text-uppercase">
      <%= notification.notification_type == "new_project" ? "Добавлено проект" : notification.notification_type == "new_user" ? "Новий працівник" : notification.notification_type == "join_to_project" ? "Приєднався до проекту" : "Взяв до виконання"%>
  </div>
  <% if ["Project", "User"].include?(notification.object_type) %>
    <div class="col-4">
      <%= link_to notification.object.name, notification.object, class:"fw-bold text-uppercase"%>
    </div>
  <%else%>
    <div class="col-4 fw-bold text-uppercase">
      <%= notification.object.name %>
    </div>
  <%end%>
  <% if ["User"].include?(notification.sub_object_type) %>
    <div class="col-3 ms-5 ps-5 text-end fw-bold color__gray text-uppercase">
      <%= link_to notification.sub_object.name, notification.sub_object %>
    </div>
  <%else%>
  <%end%>
  <% if notification.notification_type == "new_user"%>
    <div class="col-3 ms-5 ps-5 text-end fw-bold color__gray text-uppercase">
      <%= notification.object.position%>
    </div>
  <%end%>
</div>

app/views/projects/_project.html.erb
<div class="col-12 m-3 <%= "d-none" if ((project.finish_at.to_date - DateTime.now.to_date).to_i) < 0 %>">
  <div class="Box Box__padding">
      <div class="d-flex row">
        <div class="mb-4">
          <h3 class="Box__title mb-0">
            <%= project.name %>
              <%= image_tag "info-circle.svg", width:24, height:24, title: "Дізнатися більше", class: "pointer", data: { bs_toggle: "modal", bs_target: "#projectsModal", bs_modaltitle: project.name, bs_modaldesc: project.description, bs_project: join_project_path(project)} %>
          </h3>
          <div class="badge bage bage__top">
            Залишилось <%= (project.finish_at.to_date - DateTime.now.to_date).to_i%> днів
          </div>
        </div>
        <div class="d-flex justify-content-between align-items-end">
          <div class="d-flex row">
            <span class="mb-3 text-black-50 fw-normal">
              Старт: <span class="ms-3 text-dark fw-bolder"><%= project.start_at.strftime("%e.%m.%Y")%></span>
            </span>
            <span class="mb-3 text-black-50 fw-normal">
              Фініш: <span class="ms-3 text-dark fw-bolder"><%= project.finish_at.strftime("%e.%m.%Y")%></span>
            </span>
          </div>
          <div class="d-flex col row">
            <span class="Box__infotitle">Бюджет</span>
            <span class="Box__infotxt"><%="#{project.budget} #{project.currency}"%></span>
          </div>
          <div class="d-flex col row">
            <span class="Box__infotitle">Виконано</span>
            <span class="Box__infotxt"><%= project.completed_tasks_count %> iз <%= project.tasks_count %></span>
          </div>
          <%=link_to "Приєднатись", join_project_path(project), method: :post, class:"btn__card"%>
        </div>
      </div>
  </div>
</div>

app/views/projects/_user.html.erb
<span class="">
  <%= link_to user do %>
    <%= image_tag "/user.svg", wigth: 42, height: 42, class:"mx-1 img", alt: user.email, title: user.email %>
  <%end%>
</span>

app/views/projects/index.html.erb
<h1 class="text-center Box__maintitle my-5">Проекти</h1>
<div class="">
    <%= render @projects %>
    <% if @projects.size.zero?%>
    <h2 class="text-center">Нема доступних проектів</h2>
  <%end %>
</div>

<!-- Modal -->
<div class="modal fade" id="projectsModal" tabindex="-1" aria-labelledby="projectModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
    <div class="modal_content modal_content__padding">
      <div class="modal_header">
        <h5 class="my-0 modal_title " id="projectModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal_body">
        <p class="modal_desc pb-2">Modal body text goes here.</p>
        <a class="btn__card mt-4 modal_btn d-flex justify-content-center mx-auto" rel="nofollow" data-method="post" href="">Приєднатись</a>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<h1 class="Box__maintitle mt-5 mb-2">
  <%=@project.name%><%= image_tag "info-circle.svg", class:"pointer ms-2", width:24, height:24, data: { bs_toggle: "modal", bs_target: "#projectModal"} %>
</h1>
<div class="d-flex justify-content-between">
  <div class="Box__grey_text d-flex align-items-center">
    Учасники:
    <%= render partial: "user", collection: @users %>
  </div>
  <div class="Box__infotxt Box__colored">
    <%="#{@project.budget} #{@project.currency}"%>
  </div>
</div>
<div class="row Box Box__hs mt-4 mx-0 p-5" role="group">
  <%= render @topics %>
</div>
<%#= render "topics/form", topic: Topic.new %>
<!-- Modal -->
<div class="modal fade" id="projectModal" tabindex="-1" aria-labelledby="projectModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
    <div class="modal_content modal_content__padding">
      <div class="modal_header">
        <h5 class="my-0 modal_title " id="projectModalLabel"><%=@project.name%></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal_body">
        <p class="modal_desc"><%= raw @project.description%></p>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with model: [@project, task], id: "#{dom_id(task.topic)}_#{dom_id(task)}_form" do |f| %>
  <div class="form-floating mb-3">
    <%= f.text_field :name, class: "form-control", placeholder: "Напишіть назву задачі тут" %>
    <%= f.label :name, "Назва задачі", class: "form-floating__label" %>
  </div>
  <div class="form mb-3">
    <%= f.rich_text_area :description, id: "description_#{topic.id}", class: "form-control", placeholder: "Напишіть опис задачі тут" %>
  </div>
  <%= f.hidden_field :topic_id %>
  <div class="text-center">
    <%= f.submit "Добавити задачу", class: "btn btn__card w-100"%>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="col-12 p-2 Box Box__task Box__shadow p-1 pointer"
    data-bs-toggle="modal"
    data-bs-target="#<%=dom_id(task)%>"
>
  <%=task.name%>
  <%if task.users%>
    <div class="d-flex mt-2 justify-content-end modal_content__persons">
      <%= render partial: "user", collection: task.users  %>
    </div>
  <%end%>
</div>
<%= render "tasks/task/modal", task:task%>

app/views/tasks/_user.html.erb
<%= link_to user do %>
  <%= image_tag "/user.svg", wigth: 42, height: 42, class:"mx-1 img", alt: user.email, title: user.email %>
<%end%>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@topic)}_#{dom_id(Task.new)}_form" do %>
  <%= render 'form', task: @topic.tasks.build, topic: @topic %>
<% end %>
<%= turbo_stream.append "#{dom_id(@topic)}_list" do %>
  <%= render @task, topic: @topic %>
<% end %>

app/views/tasks/destroy.turbo_stream.erb
<%= turbo_stream.update "#{dom_id(@topic)}_list" do  %>
  <%= render @topic.tasks, topic: @topic %>
<%end%>

app/views/tasks/task/_modal.html.erb
<!-- Modal for task-->
<div class="modal md-effect-11" id="<%=dom_id(task)%>" tabindex="-1" aria-hidden="true" >
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
    <div class="modal_content modal_content__padding">
      <div class="modal_header mb-0">
        <div>
          <h5 class="my-0 modal_title"><%=task.name%></h5>
          <p class="mt-1">у списку: <span class="modal_topic"><%=task.topic.name%></span></p>
        </div>
        <button type="button" class="btn-close mb-auto" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal_body">
        <div class="row">
          <div class="col-8">
            <div class="mb-3">
              <p class="modal_content__title mb-1" >Учасники</p>
              <div class="modal_content__persons ">
                <%= render partial: "user", collection: task.users  %>
              </div>
            </div>
            <div class="mb-3">
              <h5 class="modal_content__title mb-2">Опис</h5>
              <p class="modal_desc">
                <%== task.description %>
              </p>
            </div>
          </div>
          <div class="col-4">
            <h5 class="modal_content__title">Дії</h5>
            <% unless task.users.exists?(current_user.id) %>
              <%=link_to "Приєднатись", join_task_path(task), method: :post, class:"btn btn__mark"%>
            <% end%>
            <% task.project.topics.where.not(id: task.topic_id).each do |topic|%>
              <%= link_to "Перемістити до: #{topic.name}", task_path(task, task: {topic_id: topic.id}), method: :patch, class:"btn btn__mark", data: { bs_dismiss: "modal"}%>
            <%end%>
            <%=link_to "Видалити", task_path(task), method: :delete, class:"btn btn__mark", data: { bs_dismiss: "modal"} %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/update.turbo_stream.erb
<%= turbo_stream.update "#{dom_id(@topic)}_list" do %>
  <%= render @topic.tasks, topic: @topic %>
<%end%>
<% if @topic.id != @old_topic%>
  <%= turbo_stream.update "#{dom_id(@old_topic)}_list" do %>
    <%= render @old_topic.tasks, topic: @old_topic %>
  <%end%>
<%end%>

app/views/topics/_form.html.erb
<%= form_with model: [@project, topic], id: "#{dom_id(topic)}_form" do |f| %>
  <div class="form-floating mt-5 mb-3">
    <%= f.text_field :name, class: "form-control", placeholder: "Напишіть назву категорії задач" %>
    <%= f.label :name, "Назва категорії задач", class: "form-floating__label" %>
  </div>
  <div class="text-center">
    <%= f.submit "Добавити категорію задач", class: "btn btn__card w-100"%>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div class="me-3 Box__grey_box">
  <h3 class="Box__topic text-center mt-2"><%= topic.name %></h3>
  <div class="Box__vs">
    <div class="row m-0" id=<%="#{dom_id(topic)}_list"%>>
      <%= render topic.tasks, topic: topic %>
    </div>
  </div>
  <button class="btn btn__text mt-2" data-bs-toggle="modal" data-bs-target="#addTaskModal_<%= topic.id %>"><span class="me-3">+</span>Додати задачу</button>
</div>
<div class="modal fade" id="addTaskModal_<%= topic.id %>" tabindex="-1" aria-labelledby="addTaskModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal_content modal_content__padding">
      <div class="modal_header">
        <h5 class="my-0 modal_title " id="addTaskModalLabel"><span class="fw-normal">Добавити задачу до:</span> <%=topic.name%></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal_body">
        <%= render "tasks/form", task: topic.tasks.build, topic: topic %>
      </div>
    </div>
  </div>
</div>

app/views/topics/create.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(Topic.new)}_form" do %>
  <%= render 'form', topic: Topic.new %>
<% end %>
<%= turbo_stream.append "#{dom_id(@project)}_list" do %>
  <%= render @topic %>
<% end %>

app/views/users/_user.html.erb
<li class="splide__slide w-auto">
  <div class="Box Box__usercard me-3 col-12 col-md-2">
    <div class="inner_info p-3">
      <%= link_to user, class:"img_title d-flex mb-2" do %>
        <%= image_tag "/user.svg", height: 70, alt: user.email, title: user.email %>
        <h5 class="text-center ms-3 my-auto text-break "><%= user.name %></h5>
      <%end%>
      <div class="info_list">
        <p><%== "Вік: <b>#{(Date.current.year - user.birthday_at.year)}</b> років" if user.birthday_at%></p>
        <p>Працює від: <span><%= user.created_at.strftime("%d.%m.%Y")%></span></p>
        <p>Посада: <span><%= user.position%></span></p>
        <p>Виконані проекти: <span><%= user.projects.finished.count%></span></p>
        <p>Всього проектів: <span><%= user.projects.count%></span></p>
      </div>
    </div>
  </div>
</li>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Увійти", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Забули пароль?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>